### ISSUE TITLE
Find out if composites can have several projects

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/pyoracc#42]
Nammu needs to read the project from a parsed ATF. The way it was doing it so far was like this:

```python
parsed_atf = self.parse(nammu_text)
project = parsed_atf.text.project
```

However this only works for non composites, since composites can have more than one text element, each having it's own PROJECT token.

I haven't looked through the whole corpus but had a look at several of the composites and all the texts inside seem to belong to the same project. 

When sending the SOAP envelope for the validation, one project name needs to be specified, so it makes sense it is unique through the file, although it doesn't make sense the original ORACC grammar includes the PROJECT token in all elements of a composite if it's going to be the same. 

Need to clarify this with Steve/Eleanor to make sure the contents of the soap envelope are correct.

**Comment by jenshnielsen** [comment]
This is not actually an issue as such but a misunderstanding of terms
Composites  are marked with `@composite` and only contains one project line the files 
with more than one project line are a gathering of small files. And they always have the same project. See #51 @raquel-ucl I think this can close?

**Comment by raquel-ucl** [comment]
Yep. Closing.
