### ISSUE TITLE
Make pyoracc available on PyPi

### ISSUE THREAD

**Issue by ageorgou** [oracc/pyoracc#67]
This might make it simpler to include pyoracc as a dependency when building Nammu, as well as making this more widely available.

**Comment by raquel-ucl** [comment]
See http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by jayanthjaiswal** [comment]
@raquel-ucl I can do this. Already have packaged it properly. Please accept my changes.

**Comment by jayanthjaiswal** [comment]
@ageorgou it is now done. Check it out here:
https://pypi.org/project/pyoracc/
Please close this issue.

**Comment by ageorgou** [comment]
Thanks @jayanthjaiswal! Closing after #73.
